favicon: /img/avatar.png

apple_touch_icon: /img/avatar.png
tab_title_separator: " - "
force_https: false
code:
  copy_btn: true
  language:
    enable: true
    default: "TEXT"
  highlight:
    enable: true
    line_number: true
    lib: "highlightjs"

    highlightjs:
      style: "github gist"
      style_dark: "dark"

    prismjs:
      style: "default"
      style_dark: "tomorrow night"
      preprocess: true


fun_features:
  typing:
    enable: true
    typeSpeed: 70
    cursorChar: "_"
    loop: false
    # Options: home | post | tag | category | about | links | page | 404
    scope: []

  anchorjs:
    enable: true
    element: h1,h2,h3,h4,h5,h6
    placement: right
    visible: hover
    icon: ""

  progressbar:
    enable: true
    height_px: 3
    color: "#29d"
    options: { showSpinner: false, trickleSpeed: 100 }


dark_mode:
  enable: true
  default: auto


color:

  body_bg_color: "#eee"
  body_bg_color_dark: "#181c27"
  navbar_bg_color: "#2f4154"
  navbar_bg_color_dark: "#1f3144"
  navbar_text_color: "#fff"
  navbar_text_color_dark: "#d0d0d0"
  subtitle_color: "#fff"
  subtitle_color_dark: "#d0d0d0"
  text_color: "#3c4858"
  text_color_dark: "#c4c6c9"
  sec_text_color: "#718096"
  sec_text_color_dark: "#a7a9ad"
  board_color: "#fff"
  board_color_dark: "#252d38"
  post_text_color: "#2c3e50"
  post_text_color_dark: "#c4c6c9"
  post_heading_color: "#1a202c"
  post_heading_color_dark: "#c4c6c9"
  post_link_color: "#0366d6"
  post_link_color_dark: "#1589e9"
  link_hover_color: "#30a9de"
  link_hover_color_dark: "#30a9de"
  link_hover_bg_color: "#f8f9fa"
  link_hover_bg_color_dark: "#364151"
  line_color: "#eaecef"
  line_color_dark: "#435266"
  scrollbar_color: "#c4c6c9"
  scrollbar_color_dark: "#687582"
  scrollbar_hover_color: "#a6a6a6"
  scrollbar_hover_color_dark: "#9da8b3"
  button_bg_color: "transparent"
  button_bg_color_dark: "transparent"
  button_hover_bg_color: "#f2f3f5"
  button_hover_bg_color_dark: "#46647e"


font:
  font_size: 16px
  font_family:
  letter_spacing: 0.02em
  code_font_size: 85%
custom_js:
custom_css:


web_analytics:  # 网页访问统计
  enable: false
  follow_dnt: true
  baidu:
  google:
    measurement_id:
  tencent:
    sid:
    cid:
  woyaola:
  cnzz:
  leancloud:
    app_id:
    app_key:
    server_url:
    path: window.location.pathname
    ignore_local: false


lazyload:
  enable: true
  loading_img: /img/loading.gif
  onlypost: false
  offset_factor: 2


iconfont: //at.alicdn.com/t/font_1736178_lbnruvf0jn.css


navbar:
  blog_title: "LL"

  ground_glass:
    enable: false
    px: 3
    alpha: 0.7

  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }    
    # - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill" }
    # - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }
    #- { key: "links", link: "/links/", icon: "iconfont icon-link-fill" }

search:
  enable: true
  path: /local-search.xml
  generate_path: /local-search.xml
  field: post
  content: true


banner:
  parallax: true
  width_height_ratio: 1.0


scroll_down_arrow:
  enable: true
  banner_height_limit: 80
  scroll_after_turning_page: true

scroll_top_arrow:
  enable: true

# Open Graph metadata
# See: https://hexo.io/docs/helpers.html#open-graph
open_graph:
  enable: true
  twitter_card: summary_large_image
  twitter_id:
  twitter_site:
  google_plus:
  fb_admins:
  fb_app_id:


footer:
  content: '
    <a href="https://hexo.io" target="_blank" rel="nofollow noopener"><span>Hexo</span></a>
    <i class="iconfont icon-love"></i>
    <a href="https://github.com/fluid-dev/hexo-theme-fluid" target="_blank" rel="nofollow noopener"><span>Fluid</span></a>
  '

  statistics:
    enable: false
    source: "busuanzi"
  beian:
    enable: false
    icp_text: 京ICP证123456号
    police_text: 京公网安备12345678号
    police_code: 12345678
    police_icon: /img/police_beian.png


#---------------------------
# 首页
# Home Page
#---------------------------
index:
  banner_img: /img/banner.jpg
  banner_img_height: 85
  banner_mask_alpha: 0
  slogan:
    enable: true
    text: "曾是惊鸿照影来"
    api:
      enable: false
      url: ""
      method: "GET"
      headers: {}
      keys: []

  auto_excerpt:
    enable: false

  post_url_target: _self

  post_meta:
    date: true
    category: true
    tag: true


  post_sticky:
    enable: true
    icon: "iconfont icon-top"


#---------------------------
# 文章页
# Post Page
#---------------------------
post:
  banner_img: /img/banner.jpg
  banner_img_height: 30
  banner_mask_alpha: 0.3
  default_index_img:

  meta:

    author:
      enable: false

    date:
      enable: true
      format: "LL a"

    wordcount:
      enable: true

    min2read:
      enable: true
      awl: 2
      wpm: 60

    views:
      enable: false
      source: "busuanzi"

  updated:
    enable: true
    date_format: "LL a"
    relative: true
    note_class: info

  category_bar:
    enable: true
    specific: truet
    placement: left
    post_order_by: "title"
    post_limit: 0

  toc:
    enable: true
    placement: right
    headingSelector: "h1,h2,h3,h4"
    collapseDepth: 0

  copyright:
    enable: false
    license: 'BY'
    author:
      enable: true
    post_date:
      enable: true
      format: "LL"
    update_date:
      enable: false
      format: "LL"

  prev_next:
    enable: true

  image_caption:
    enable: true

  image_zoom:
    enable: true
    img_url_replace: ['', '']

  footnote:
    enable: true
    header: ''

  math:
    enable: false
    specific: false
    engine: mathjax

  mermaid:
    enable: false
    specific: false
    options: { theme: 'default' }

  comments:
    enable: false
    type: disqus


#---------------------------
# 评论插件
# Comment plugins
#
# 开启评论需要先设置上方 `post: comments: enable: true`，然后根据 `type` 设置下方对应的评论插件参数
# Enable comments need to be set `post: comments: enable: true`, then set the corresponding comment plugin parameters below according to `type`
#---------------------------
utterances:
  repo:
  issue_term: pathname
  label: utterances
  theme: github-light
  theme_dark: github-dark

disqus:
  shortname:
  disqusjs: false
  apikey:

gitalk:
  clientID:
  clientSecret:
  repo:
  owner:
  admin: ['name']
  language: zh-CN
  labels: ['Gitalk']
  perPage: 10
  pagerDirection: last
  distractionFreeMode: false
  createIssueManually: true
  proxy: https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token

valine:
  appId:
  appKey:
  path: window.location.pathname
  placeholder:
  avatar: 'retro'
  meta: ['nick', 'mail', 'link']
  requiredFields: []
  pageSize: 10
  lang: 'zh-CN'
  highlight: false
  recordIP: false
  serverURLs: ''
  emojiCDN:
  emojiMaps:
  enableQQ: false

waline:
  serverURL: ''
  path: window.location.pathname
  meta: ['nick', 'mail', 'link']
  requiredMeta: ['nick']
  lang: 'zh-CN'
  emoji: ['https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo']
  dark: 'html[data-user-color-scheme="dark"]'
  wordLimit: 0
  pageSize: 10

changyan:
  appid: ''
  appkey: ''

livere:
  uid: ''

remark42:
  host:
  site_id:
  max_shown_comments: 10
  locale: zh
  components: ['embed']

twikoo:
  envId:
  region: ap-shanghai
  path: window.location.pathname

cusdis:
  host:
  app_id:
  lang: zh-cn

giscus:
  repo:
  repo-id:
  category:
  category-id:
  theme-light: light
  theme-dark: dark
  mapping: pathname
  reactions-enabled: 1
  emit-metadata: 0
  input-position: top
  lang: zh-CN

discuss:
  serverURLs:
  path: window.location.pathname


#---------------------------
# 归档页
# Archive Page
#---------------------------
archive:
  banner_img: /img/banner.jpg
  banner_img_height: 30
  banner_mask_alpha: 0.3


#---------------------------
# 分类页
# Category Page
#---------------------------
category:
  enable: true
  banner_img: /img/banner.jpg
  banner_img_height: 30
  banner_mask_alpha: 0.3
  order_by: "-length"
  collapse_depth: 0
  post_order_by: "-date"
  post_limit: 10


#---------------------------
# 标签页
# Tag Page
#---------------------------
tag:
  enable: true
  banner_img: /img/banner.jpg
  banner_img_height: 30
  banner_mask_alpha: 0.3
  tagcloud:
    min_font: 15
    max_font: 30
    unit: px
    start_color: "#BBBBEE"
    end_color: "#337ab7"


#---------------------------
# 关于页
# About Page
#---------------------------
about:
  enable: true
  banner_img: /img/banner.jpg
  banner_img_height: 30
  banner_mask_alpha: 0.3
  avatar: /img/avatar.webp
  name: "ll"
  intro: "An elegant theme for Hexo"
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com", tip: "GitHub" }
    - { class: "iconfont icon-douban-fill", link: "https://douban.com", tip: "豆瓣" }
    - { class: "iconfont icon-wechat-fill", qrcode: "/img/favicon.png" }


#---------------------------
# 自定义页
# Custom Page
#
# 通过 hexo new page 命令创建的页面
# Custom Page through `hexo new page`
#---------------------------
page:
  banner_img: /img/banner.jpg
  banner_img_height: 30
  banner_mask_alpha: 0.3


#---------------------------
# 404页
# 404 Page
#---------------------------
page404:
  enable: true
  banner_img: /img/banner.jpg
  banner_img_height: 30
  banner_mask_alpha: 0.3
  subtitle: "Page not found"
  redirect_delay: 5000


#---------------------------
# 友链页
# Links Page
#---------------------------
links:
  enable: false
  banner_img: /img/banner.jpg
  banner_img_height: 30
  banner_mask_alpha: 0.3
  items:
    - {
      title: "Fluid Blog",
      intro: "主题博客",
      link: "https://hexo.fluid-dev.com/",
      avatar: "/img/favicon.png"
    }
    - {
      title: "Fluid Docs",
      intro: "主题使用指南",
      link: "https://hexo.fluid-dev.com/docs/",
      avatar: "/img/favicon.png"
    }
    - {
      title: "Fluid Repo",
      intro: "主题 GitHub 仓库",
      link: "https://github.com/fluid-dev/hexo-theme-fluid",
      avatar: "/img/favicon.png"
    }


  onerror_avatar: /img/avatar.png


  custom:
    enable: false
    content: '<hr><p>在下方留言申请加入我的友链，按如下格式提供信息：</p><ul><li>博客名：Fluid</li><li>简介：Fluid 主题官方博客</li><li>链接：https://hexo.fluid-dev.com</li><li>图片：https://hexo.fluid-dev.com/img/favicon.png</li></ul>'

  comments:
    enable: false
    type: disqus


static_prefix:
  internal_js: /js
  internal_css: /css
  internal_img: /img
  anchor: https://lib.baomitu.com/anchor-js/4.3.1/
  github_markdown: https://lib.baomitu.com/github-markdown-css/4.0.0/
  jquery: https://lib.baomitu.com/jquery/3.6.4/
  bootstrap: https://lib.baomitu.com/twitter-bootstrap/4.6.1/
  prismjs: https://lib.baomitu.com/prism/1.29.0/
  tocbot: https://lib.baomitu.com/tocbot/4.20.1/
  typed: https://lib.baomitu.com/typed.js/2.0.12/
  fancybox: https://lib.baomitu.com/fancybox/3.5.7/
  nprogress: https://lib.baomitu.com/nprogress/0.2.0/
  mathjax: https://lib.baomitu.com/mathjax/3.2.2/
  katex: https://lib.baomitu.com/KaTeX/0.16.2/
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/
  clipboard: https://lib.baomitu.com/clipboard.js/2.0.11/
  mermaid: https://lib.baomitu.com/mermaid/8.14.0/
  valine: https://lib.baomitu.com/valine/1.5.1/
  waline: https://cdn.staticfile.org/waline/2.15.5/
  gitalk: https://lib.baomitu.com/gitalk/1.8.0/
  disqusjs: https://lib.baomitu.com/disqusjs/1.3.0/
  twikoo: https://lib.baomitu.com/twikoo/1.6.8/
  discuss: https://lib.baomitu.com/discuss/1.2.1/
  hint: https://lib.baomitu.com/hint.css/2.7.0/
  moment: https://lib.baomitu.com/moment.js/2.29.4/
