name: deploy hexo page

on:
  push:
    branches:
      - main
  release:
    type:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: install hexo
      run: |
        export TZ='Asia/Shanghai'
        npm install hexo-cli -g
        npm install --save
    - name: generate
      run: |
        hexo clean
        hexo generate
    - name: deploy
      run: |
        cd ./public
        git init
        git config --global user.name '${{ secrets.USERNAME }}'
        git config --global user.email '${{ secrets.EMAIL }}'
        git branch -m main
        git add .
        git commit -m "Site updated: $(date +"%Y-%m-%d %A %H:%M:%S")"
        git push --force --quiet "https://${{ secrets.USERNAME }}:${{ secrets.TOKEN }}@github.com/${{ secrets.USERNAME }}/${{ secrets.USERNAME }}.github.io.git" main
